[project]
name = "python-api"
version = "0.1.0"
description = "AI Support Co-Pilot API"
requires-python = "==3.11.*"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-dotenv",
    "langchain",
    "langchain-openai",
    "supabase",
    "pydantic"
]